### PR TITLE
Make libdir a mandatory parameter to 'applyRefactorings'

### LINKED ISSUE #133: Apply-refact shouldn't hardcode `GHC.Paths.libdir` in `parseModuleWithArgs`
From https://github.com/haskell/haskell-language-server/issues/3241, we essentially traced the issue to https://github.com/mpickering/apply-refact/blob/master/src/Refact/Internal.hs#L718. 
Our binary distribution uses the wrong libdir because of ghc-paths.

The solution is to allow us to specify the libdir in `parseModuleWithArgs`, since we do know it.
Additionally, every usage of `parseModuleWithArgs` needs to propagate this parameter requirement.

### PR DESCRIPTION
**Pull request by fendor**
Binary distributions of programs depending on apply-refact are otherwise impossible, since the distributed package will contain a hard-coded path to a libdir to a GHC installation on the host system.

Fixes #133

### CODE REVIEW

File: src/Refact/Run.hs [hunk 1]
```diff
@@ -87,7 +88,7 @@ runPipe Options {..} file = do
           "Invalid extensions: " ++ intercalate ", " invalidExts
         m <-
           either (onError "runPipe") applyFixities
-            =<< parseModuleWithArgs (enabledExts, disabledExts) file
+            =<< parseModuleWithArgs GHC.Paths.libdir (enabledExts, disabledExts) file
```
Comment (hasufell) [inline src/Refact/Run.hs:91]: Sorry, I don't understand how this fixes it. We're still using GHC.Paths.libdir here? It seems the invocation just moved.

Comment (fendor) [reply src/Refact/Run.hs:91]: Yeah but thats the executable. The library of apply refract doesn't use it anymore. This allows the binary of apply refact to continue to work without a major overhaul

Comment (fendor) [reply src/Refact/Run.hs:91]: Yeah. Doing that right now would require to migrate them to hie-bios (or cli argument), which I am to do, but for HLS, this is the important bit and apply-refact can't have a binary distribution right now either.

**Review by hasufell — APPROVED** [review]

File: src/Refact/Run.hs (hunk 1 above)
Comment (michaelpj) [reply src/Refact/Run.hs:91]: Why not write what you just said as a comment in the code here?

**Comment by zliu41** [comment]
LGTM, thanks for the fix. This is long overdue.

**Review by zliu41 — APPROVED** [review]

**Comment by zliu41** [comment]
0.12.0.0 published on Hackage.
